/**
 * Ledger Controller
 * ─────────────────
 * Handles administrative ledger views, paginated JSON requests, PDF rendering,
 * and multi-sheet Excel ledger downloads.
 */

const ledgerService = require("../services/ledgerService");
const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");
const { HTTP_STATUS } = require("../utils/constants");
const { formatDateTime, formatDateOnly } = require("../utils/dateHelper");

// Validate Date Range constraints
function validateDates(filter, startDate, endDate) {
  if (filter === "custom") {
    if (!startDate || !endDate) {
      return { isValid: false, message: "Both Start Date and End Date are required." };
    }

    const start = new Date(startDate);
    const end = new Date(endDate);
    const today = new Date();

    if (isNaN(start.getTime()) || isNaN(end.getTime())) {
      return { isValid: false, message: "Invalid date format." };
    }

    if (end < start) {
      return { isValid: false, message: "End date cannot be earlier than start date." };
    }

    if (start > today || end > today) {
      return { isValid: false, message: "Future dates are not allowed." };
    }
  }
  return { isValid: true };
}

/**
 * Render the Ledger page view
 */
exports.renderLedger = async (req, res) => {
  try {
    res.render("admin/ledger", {
      title: "Ledger Book - KAVOX Admin",
      activePage: "ledger"
    });
  } catch (error) {
    console.error("Render Ledger Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).send("Failed to render ledger book page.");
  }
};

/**
 * GET /admin/ledger/data
 * Returns paginated ledger entries as JSON
 */
exports.getLedgerDataAPI = async (req, res) => {
  try {
    const { filter = "monthly", startDate, endDate } = req.query;
    const page = parseInt(req.query.page) || 1;
    const limit = 15;
    const skip = (page - 1) * limit;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).json({ success: false, message: validation.message });
    }

    const ledgerData = await ledgerService.getLedgerEntries(filter, startDate, endDate);
    
    // Paginate in JS to preserve exact chronology sorting and balances
    const paginatedEntries = ledgerData.entries.slice(skip, skip + limit);
    const totalPages = Math.ceil(ledgerData.entries.length / limit) || 1;

    res.status(HTTP_STATUS.OK).json({
      success: true,
      entries: paginatedEntries,
      summary: ledgerData.summary,
      page,
      totalPages,
      totalEntries: ledgerData.entries.length
    });
  } catch (error) {
    console.error("Get Ledger Data Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).json({
      success: false,
      message: "Failed to load ledger transactions."
    });
  }
};

/**
 * GET /admin/ledger/download/pdf
 * Generates and downloads PDF general ledger
 */
exports.downloadLedgerPdf = async (req, res) => {
  try {
    const { filter = "monthly", startDate, endDate } = req.query;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).send(validation.message);
    }

    const ledgerData = await ledgerService.getLedgerEntries(filter, startDate, endDate);

    const doc = new PDFDocument({ margin: 30, size: "A4", layout: "landscape" });
    
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="KAVOX-general-ledger-${filter}-${Date.now()}.pdf"`);
    
    doc.pipe(res);

    // Header Design
    doc.fontSize(22).fillColor("#0f172a").text("KAVOX SOLE LAB", { align: "center", font: "Helvetica-Bold" });
    doc.fontSize(12).fillColor("#64748b").text("GENERAL LEDGER BOOK & STATEMENT OF ACCOUNTS", { align: "center" });
    doc.moveDown(0.8);

    // Meta Block
    const dateRangeStr = `${formatDateOnly(ledgerData.dateRange.start)} to ${formatDateOnly(ledgerData.dateRange.end)}`;
    doc.fontSize(9).fillColor("#334155");
    doc.text(`Statement Level: ${filter.toUpperCase()}`);
    doc.text(`Generated By: KAVOX System Administrator`);
    doc.text(`Time window: ${dateRangeStr}`);
    doc.text(`Run Date: ${formatDateTime(new Date())}`);
    doc.moveDown(1.5);

    // Summary section card background
    doc.rect(30, doc.y, 781.89, 50).fill("#f8fafc");
    doc.fillColor("#0f172a");

    const yVal = doc.y + 12;
    doc.fontSize(8).fillColor("#64748b").text("TOTAL TRANSACTIONS", 40, yVal, { width: 180, align: "center" });
    doc.fontSize(11).fillColor("#0f172a").text(`${ledgerData.entries.length} Entries`, 40, yVal + 12, { width: 180, align: "center", font: "Helvetica-Bold" });

    doc.fontSize(8).fillColor("#64748b").text("TOTAL DEBITS (OUTFLOWS)", 240, yVal, { width: 180, align: "center" });
    doc.fontSize(11).fillColor("#ef4444").text(`₹${ledgerData.summary.totalDebit.toLocaleString()}`, 240, yVal + 12, { width: 180, align: "center" });

    doc.fontSize(8).fillColor("#64748b").text("TOTAL CREDITS (INFLOWS)", 440, yVal, { width: 180, align: "center" });
    doc.fontSize(11).fillColor("#10b981").text(`₹${ledgerData.summary.totalCredit.toLocaleString()}`, 440, yVal + 12, { width: 180, align: "center" });

    doc.fontSize(8).fillColor("#64748b").text("CLOSING LEDGER BALANCE", 640, yVal, { width: 140, align: "center" });
    doc.fontSize(11).fillColor("#1e293b").text(`₹${ledgerData.summary.closingBalance.toLocaleString()}`, 640, yVal + 12, { width: 140, align: "center" });

    doc.y = yVal + 38;
    doc.moveDown(2);

    // Ledger Table Header
    const tableHeaderY = doc.y;
    doc.rect(30, tableHeaderY, 781.89, 20).fill("#0f172a");
    doc.fillColor("#ffffff").fontSize(8);
    
    let currentX = 35;
    doc.text("Date & Time", currentX, tableHeaderY + 6, { width: 110 });
    currentX += 110;
    doc.text("Transaction Type", currentX, tableHeaderY + 6, { width: 170 });
    currentX += 170;
    doc.text("Reference ID", currentX, tableHeaderY + 6, { width: 125 });
    currentX += 125;
    doc.text("Debit (INR)", currentX, tableHeaderY + 6, { width: 110, align: "right" });
    currentX += 110;
    doc.text("Credit (INR)", currentX, tableHeaderY + 6, { width: 110, align: "right" });
    currentX += 110;
    doc.text("Account Balance", currentX, tableHeaderY + 6, { width: 125, align: "right" });

    doc.y = tableHeaderY + 20;
    doc.fillColor("#334155").fontSize(7.5);
    let rowY = doc.y;

    if (ledgerData.entries.length === 0) {
      doc.text("No transactions found in this ledger period.", 30, rowY + 10, { align: "center" });
    } else {
      ledgerData.entries.forEach(e => {
        if (rowY > 500) {
          doc.addPage({ size: "A4", layout: "landscape", margin: 30 });
          rowY = 35;
          doc.rect(30, rowY, 781.89, 20).fill("#0f172a");
          doc.fillColor("#ffffff").fontSize(8);
          let hX = 35;
          doc.text("Date & Time", hX, rowY + 6, { width: 110 });
          hX += 110;
          doc.text("Transaction Type", hX, rowY + 6, { width: 170 });
          hX += 170;
          doc.text("Reference ID", hX, rowY + 6, { width: 125 });
          hX += 125;
          doc.text("Debit (INR)", hX, rowY + 6, { width: 110, align: "right" });
          hX += 110;
          doc.text("Credit (INR)", hX, rowY + 6, { width: 110, align: "right" });
          hX += 110;
          doc.text("Account Balance", hX, rowY + 6, { width: 125, align: "right" });
          rowY += 20;
          doc.fillColor("#334155").fontSize(7.5);
        }

        let cellX = 35;
        const formattedDate = formatDateTime(e.date);
        doc.text(formattedDate, cellX, rowY + 5, { width: 110 });
        cellX += 110;
        doc.text(e.type, cellX, rowY + 5, { width: 170 });
        cellX += 170;
        doc.text(e.referenceId, cellX, rowY + 5, { width: 125 });
        cellX += 125;
        
        const debitText = e.debit > 0 ? `₹${e.debit.toLocaleString()}` : "-";
        doc.text(debitText, cellX, rowY + 5, { width: 110, align: "right" });
        cellX += 110;
        
        const creditText = e.credit > 0 ? `₹${e.credit.toLocaleString()}` : "-";
        doc.text(creditText, cellX, rowY + 5, { width: 110, align: "right" });
        cellX += 110;

        doc.text(`₹${e.balance.toLocaleString()}`, cellX, rowY + 5, { width: 125, align: "right", font: "Helvetica-Bold" });

        // separator line
        doc.moveTo(30, rowY + 16).lineTo(811.89, rowY + 16).strokeColor("#cbd5e1").lineWidth(0.4).stroke();
        rowY += 18;
      });
    }

    doc.fontSize(8).fillColor("#94a3b8");
    doc.text("Automated System Document  |  General Ledger Statement  |  Generation: " + formatDateTime(new Date()), 30, 560, { align: "center" });
    doc.end();
  } catch (error) {
    console.error("Ledger PDF Download Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).send("Failed to export ledger PDF.");
  }
};

/**
 * GET /admin/ledger/download/excel
 * Generates and downloads Excel workbook
 */
exports.downloadLedgerExcel = async (req, res) => {
  try {
    const { filter = "monthly", startDate, endDate } = req.query;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).send(validation.message);
    }

    const ledgerData = await ledgerService.getLedgerEntries(filter, startDate, endDate);

    const workbook = new ExcelJS.Workbook();

    // Sheet 1: Ledger Summary KPI
    const summarySheet = workbook.addWorksheet("Ledger Summary");
    summarySheet.columns = [
      { header: "LEDGER KPI METRIC", key: "metric", width: 35 },
      { header: "STATEMENT VALUE", key: "value", width: 25 }
    ];
    summarySheet.addRow({ metric: "Total Placed Transactions", value: ledgerData.entries.length });
    summarySheet.addRow({ metric: "Total Debits (Outflows)", value: ledgerData.summary.totalDebit });
    summarySheet.addRow({ metric: "Total Credits (Inflows)", value: ledgerData.summary.totalCredit });
    summarySheet.addRow({ metric: "Closing Ledger Balance", value: ledgerData.summary.closingBalance });

    summarySheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    summarySheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };

    // Sheet 2: Ledger Table Details
    const detailsSheet = workbook.addWorksheet("Ledger Entries");
    detailsSheet.columns = [
      { header: "Transaction Date & Time", key: "date", width: 26 },
      { header: "Transaction Type", key: "type", width: 26 },
      { header: "Reference ID", key: "referenceId", width: 22 },
      { header: "Debit Amount (INR)", key: "debit", width: 20 },
      { header: "Credit Amount (INR)", key: "credit", width: 20 },
      { header: "Account Balance (INR)", key: "balance", width: 22 }
    ];

    ledgerData.entries.forEach(e => {
      detailsSheet.addRow({
        date: formatDateTime(e.date),
        type: e.type,
        referenceId: e.referenceId,
        debit: e.debit > 0 ? e.debit : "-",
        credit: e.credit > 0 ? e.credit : "-",
        balance: e.balance
      });
    });

    detailsSheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    detailsSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };

    // Sheet 3: Metadata
    const metaSheet = workbook.addWorksheet("Statement Audit");
    metaSheet.columns = [
      { header: "System Audit Field", key: "kpi", width: 30 },
      { header: "Audit Value", key: "value", width: 35 }
    ];
    metaSheet.addRow({ kpi: "Brand Store Name", value: "KAVOX SOLE LAB" });
    metaSheet.addRow({ kpi: "Report Level Type", value: filter.toUpperCase() });
    metaSheet.addRow({ kpi: "Start Date Constraint", value: formatDateTime(ledgerData.dateRange.start) });
    metaSheet.addRow({ kpi: "End Date Constraint", value: formatDateTime(ledgerData.dateRange.end) });
    metaSheet.addRow({ kpi: "Database Run Date", value: formatDateTime(new Date()) });
    metaSheet.addRow({ kpi: "Closing Ledger Balance", value: ledgerData.summary.closingBalance });

    metaSheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    metaSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", `attachment; filename="KAVOX-general-ledger-${filter}-${Date.now()}.xlsx"`);

    await workbook.xlsx.write(res);
    res.end();
  } catch (error) {
    console.error("Ledger Excel Export Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).send("Failed to export ledger Excel.");
  }
};
