/**
 * Sales Report Controller
 * ───────────────────────
 * Renders sales dashboards, provides metric endpoints, and exports
 * clean, styled PDF (via pdfkit) and Excel (via exceljs) files.
 */

const reportService = require("../services/reportService");
const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");
const { HTTP_STATUS } = require("../utils/constants");

// Validate Date Range constraints
function validateDates(filter, startDate, endDate) {
  if (filter === "custom") {
    if (!startDate || !endDate) {
      return { isValid: false, message: "Both Start Date and End Date are required." };
    }

    const start = new Date(startDate);
    const end = new Date(endDate);
    const today = new Date();

    if (isNaN(start.getTime()) || isNaN(end.getTime())) {
      return { isValid: false, message: "Invalid date format." };
    }

    if (end < start) {
      return { isValid: false, message: "End date cannot be earlier than start date." };
    }

    if (start > today || end > today) {
      return { isValid: false, message: "Future dates are not allowed." };
    }
  }
  return { isValid: true };
}

/**
 * Renders the Reports page view
 */
exports.renderReportDashboard = async (req, res) => {
  try {
    res.render("admin/report", {
      title: "Sales Report - KAVOX Admin",
      activePage: "report"
    });
  } catch (error) {
    console.error("Render Report Dashboard Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).send("Failed to render reports page.");
  }
};

/**
 * GET /admin/reports/summary
 * Returns analytics card counts and chart trends
 */
exports.getReportSummaryAPI = async (req, res) => {
  try {
    const { filter = "daily", startDate, endDate } = req.query;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).json({ success: false, message: validation.message });
    }

    const data = await reportService.getAnalyticsData(filter, startDate, endDate);
    res.status(HTTP_STATUS.OK).json({ success: true, data });
  } catch (error) {
    console.error("Get Report Summary Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).json({
      success: false,
      message: "Failed to load report summaries."
    });
  }
};

/**
 * GET /admin/reports/sales
 * Returns order details list with pagination
 */
exports.getReportSalesAPI = async (req, res) => {
  try {
    const { filter = "daily", startDate, endDate } = req.query;
    const page = parseInt(req.query.page) || 1;
    const limit = 10;
    const skip = (page - 1) * limit;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).json({ success: false, message: validation.message });
    }

    const reportData = await reportService.getSalesReportData(filter, startDate, endDate);
    
    // Paginate orders in JS to preserve exact sorting
    const paginatedOrders = reportData.orders.slice(skip, skip + limit);
    const totalPages = Math.ceil(reportData.orders.length / limit) || 1;

    res.status(HTTP_STATUS.OK).json({
      success: true,
      orders: paginatedOrders,
      summary: reportData.summary,
      page,
      totalPages
    });
  } catch (error) {
    console.error("Get Report Sales Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).json({
      success: false,
      message: "Failed to load sales rows."
    });
  }
};

/**
 * GET /admin/reports/download/pdf
 * Generates and downloads PDF file
 */
exports.downloadPdfReport = async (req, res) => {
  try {
    const { filter = "daily", startDate, endDate } = req.query;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).send(validation.message);
    }

    const reportData = await reportService.getSalesReportData(filter, startDate, endDate);

    const doc = new PDFDocument({ margin: 30, size: "A4", layout: "landscape" });
    
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="KAVOX-sales-report-${filter}-${Date.now()}.pdf"`);
    
    doc.pipe(res);

    // Header Design
    doc.fontSize(22).fillColor("#0f172a").text("KAVOX e-STORE", { align: "center", font: "Helvetica-Bold" });
    doc.fontSize(12).fillColor("#64748b").text("SALES PERFORMANCE REPORT", { align: "center" });
    doc.moveDown(0.8);

    // Meta Block
    const dateRangeStr = `${reportData.dateRange.start.toLocaleDateString("en-IN")} to ${reportData.dateRange.end.toLocaleDateString("en-IN")}`;
    doc.fontSize(9).fillColor("#334155");
    doc.text(`Report Level: ${filter.toUpperCase()}`);
    doc.text(`Generated By: KAVOX System Administrator`);
    doc.text(`Time window: ${dateRangeStr}`);
    doc.text(`Run Date: ${new Date().toLocaleString("en-IN")}`);
    doc.moveDown(1.5);

    // Summary section card background
    doc.rect(30, doc.y, 781.89, 50).fill("#f8fafc");
    doc.fillColor("#0f172a");

    const yVal = doc.y + 12;
    doc.fontSize(8).fillColor("#64748b").text("TOTAL ORDERS", 40, yVal, { width: 130, align: "center" });
    doc.fontSize(11).fillColor("#0f172a").text(`${reportData.summary.totalOrders} Orders`, 40, yVal + 12, { width: 130, align: "center", font: "Helvetica-Bold" });

    doc.fontSize(8).fillColor("#64748b").text("GROSS REVENUE", 185, yVal, { width: 130, align: "center" });
    doc.fontSize(11).fillColor("#0f172a").text(`₹${reportData.summary.grossSales.toLocaleString()}`, 185, yVal + 12, { width: 130, align: "center" });

    doc.fontSize(8).fillColor("#64748b").text("OFFER SAVINGS", 330, yVal, { width: 130, align: "center" });
    doc.fontSize(11).fillColor("#0f172a").text(`₹${reportData.summary.offerDiscounts.toLocaleString()}`, 330, yVal + 12, { width: 130, align: "center" });

    doc.fontSize(8).fillColor("#64748b").text("COUPON SAVINGS", 475, yVal, { width: 130, align: "center" });
    doc.fontSize(11).fillColor("#0f172a").text(`₹${reportData.summary.couponDiscounts.toLocaleString()}`, 475, yVal + 12, { width: 130, align: "center" });

    doc.fontSize(8).fillColor("#64748b").text("NET REVENUE", 620, yVal, { width: 130, align: "center" });
    doc.fontSize(11).fillColor("#15803d").text(`₹${reportData.summary.netRevenue.toLocaleString()}`, 620, yVal + 12, { width: 130, align: "center" });

    doc.y = yVal + 38;
    doc.moveDown(2);

    // Sales Table Header
    const tableHeaderY = doc.y;
    doc.rect(30, tableHeaderY, 781.89, 20).fill("#0f172a");
    doc.fillColor("#ffffff").fontSize(8);
    
    let currentX = 35;
    doc.text("Order ID", currentX, tableHeaderY + 6, { width: 95 });
    currentX += 95;
    doc.text("Date", currentX, tableHeaderY + 6, { width: 75 });
    currentX += 75;
    doc.text("Customer", currentX, tableHeaderY + 6, { width: 110 });
    currentX += 110;
    doc.text("Payment", currentX, tableHeaderY + 6, { width: 70 });
    currentX += 70;
    doc.text("Gross", currentX, tableHeaderY + 6, { width: 70, align: "right" });
    currentX += 70;
    doc.text("Offer Disc.", currentX, tableHeaderY + 6, { width: 70, align: "right" });
    currentX += 70;
    doc.text("Coupon", currentX, tableHeaderY + 6, { width: 70, align: "right" });
    currentX += 70;
    doc.text("Final Paid", currentX, tableHeaderY + 6, { width: 80, align: "right" });
    currentX += 80;
    doc.text("Status", currentX, tableHeaderY + 6, { width: 65, align: "center" });

    doc.y = tableHeaderY + 20;
    doc.fillColor("#334155").fontSize(7);
    let rowY = doc.y;

    if (reportData.orders.length === 0) {
      doc.text("No matching delivered sales found in database.", 30, rowY + 10, { align: "center" });
    } else {
      reportData.orders.forEach(o => {
        if (rowY > 500) {
          doc.addPage({ size: "A4", layout: "landscape", margin: 30 });
          rowY = 35;
          doc.rect(30, rowY, 781.89, 20).fill("#0f172a");
          doc.fillColor("#ffffff").fontSize(8);
          let hX = 35;
          doc.text("Order ID", hX, rowY + 6, { width: 95 });
          hX += 95;
          doc.text("Date", hX, rowY + 6, { width: 75 });
          hX += 75;
          doc.text("Customer", hX, rowY + 6, { width: 110 });
          hX += 110;
          doc.text("Payment", hX, rowY + 6, { width: 70 });
          hX += 70;
          doc.text("Gross", hX, rowY + 6, { width: 70, align: "right" });
          hX += 70;
          doc.text("Offer Disc.", hX, rowY + 6, { width: 70, align: "right" });
          hX += 70;
          doc.text("Coupon", hX, rowY + 6, { width: 70, align: "right" });
          hX += 70;
          doc.text("Final Paid", hX, rowY + 6, { width: 80, align: "right" });
          hX += 80;
          doc.text("Status", hX, rowY + 6, { width: 65, align: "center" });
          rowY += 20;
          doc.fillColor("#334155").fontSize(7);
        }

        let cellX = 35;
        doc.text(o.orderId, cellX, rowY + 5, { width: 95 });
        cellX += 95;
        doc.text(new Date(o.date).toLocaleDateString("en-IN"), cellX, rowY + 5, { width: 75 });
        cellX += 75;
        const nameText = o.customer.length > 20 ? o.customer.substring(0, 17) + "..." : o.customer;
        doc.text(nameText, cellX, rowY + 5, { width: 110 });
        cellX += 110;
        doc.text(o.paymentMethod, cellX, rowY + 5, { width: 70 });
        cellX += 70;
        doc.text(`₹${o.grossAmount.toLocaleString()}`, cellX, rowY + 5, { width: 70, align: "right" });
        cellX += 70;
        doc.text(`₹${o.offerDiscount.toLocaleString()}`, cellX, rowY + 5, { width: 70, align: "right" });
        cellX += 70;
        doc.text(`₹${o.couponDiscount.toLocaleString()}`, cellX, rowY + 5, { width: 70, align: "right" });
        cellX += 70;
        doc.text(`₹${o.finalAmount.toLocaleString()}`, cellX, rowY + 5, { width: 80, align: "right" });
        cellX += 80;
        doc.text(o.status, cellX, rowY + 5, { width: 65, align: "center" });

        // separator line
        doc.moveTo(30, rowY + 16).lineTo(811.89, rowY + 16).strokeColor("#cbd5e1").lineWidth(0.4).stroke();
        rowY += 18;
      });
    }

    doc.fontSize(8).fillColor("#94a3b8");
    doc.text("Automated System Document  |  Generation: " + new Date().toLocaleString("en-IN"), 30, 560, { align: "center" });
    doc.end();
  } catch (error) {
    console.error("PDF Download Controller Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).send("Failed to export PDF.");
  }
};

/**
 * GET /admin/reports/download/excel
 * Generates and downloads Excel workbook
 */
exports.downloadExcelReport = async (req, res) => {
  try {
    const { filter = "daily", startDate, endDate } = req.query;

    const validation = validateDates(filter, startDate, endDate);
    if (!validation.isValid) {
      return res.status(HTTP_STATUS.BAD_REQUEST).send(validation.message);
    }

    const reportData = await reportService.getSalesReportData(filter, startDate, endDate);

    const workbook = new ExcelJS.Workbook();

    // Sheet 1: Sales Summary
    const summarySheet = workbook.addWorksheet("Sales Summary");
    summarySheet.columns = [
      { header: "SALES KPI METRIC", key: "metric", width: 30 },
      { header: "REPORT VALUE", key: "value", width: 25 }
    ];
    summarySheet.addRow({ metric: "Total Placed Orders", value: reportData.summary.totalOrders });
    summarySheet.addRow({ metric: "Gross Sales Revenue", value: reportData.summary.grossSales });
    summarySheet.addRow({ metric: "Product Offer Deductions", value: reportData.summary.productOfferDiscounts });
    summarySheet.addRow({ metric: "Category Offer Deductions", value: reportData.summary.categoryOfferDiscounts });
    summarySheet.addRow({ metric: "Coupon Discounts Deductions", value: reportData.summary.couponDiscounts });
    summarySheet.addRow({ metric: "Total Deductions", value: reportData.summary.discounts });
    summarySheet.addRow({ metric: "Net Revenue Yield", value: reportData.summary.netRevenue });

    // Format headers
    summarySheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    summarySheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };

    // Sheet 2: Order Details
    const detailsSheet = workbook.addWorksheet("Order Details");
    detailsSheet.columns = [
      { header: "Order ID", key: "orderId", width: 22 },
      { header: "Date Placed", key: "date", width: 18 },
      { header: "Customer Name", key: "customer", width: 28 },
      { header: "Payment Type", key: "paymentMethod", width: 18 },
      { header: "Gross Sales Amount (INR)", key: "grossAmount", width: 24 },
      { header: "Offer Savings (INR)", key: "offerDiscount", width: 22 },
      { header: "Coupon Savings (INR)", key: "couponDiscount", width: 22 },
      { header: "Net Amount Paid (INR)", key: "finalAmount", width: 24 },
      { header: "Shipping Status", key: "status", width: 18 }
    ];

    reportData.orders.forEach(o => {
      detailsSheet.addRow({
        orderId: o.orderId,
        date: new Date(o.date).toLocaleDateString("en-IN") + " " + new Date(o.date).toLocaleTimeString("en-IN"),
        customer: o.customer,
        paymentMethod: o.paymentMethod,
        grossAmount: o.grossAmount,
        offerDiscount: o.offerDiscount,
        couponDiscount: o.couponDiscount,
        finalAmount: o.finalAmount,
        status: o.status
      });
    });

    detailsSheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    detailsSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };

    // Sheet 3: Analytics Summary
    const analyticsSheet = workbook.addWorksheet("Analytics Summary");
    analyticsSheet.columns = [
      { header: "System Identifier", key: "kpi", width: 30 },
      { header: "Summary Value", key: "value", width: 35 }
    ];
    analyticsSheet.addRow({ kpi: "Brand Store Name", value: "KAVOX SOLE LAB" });
    analyticsSheet.addRow({ kpi: "Report Level Type", value: filter.toUpperCase() });
    analyticsSheet.addRow({ kpi: "Start Date Constraint", value: reportData.dateRange.start.toLocaleString("en-IN") });
    analyticsSheet.addRow({ kpi: "End Date Constraint", value: reportData.dateRange.end.toLocaleString("en-IN") });
    analyticsSheet.addRow({ kpi: "Database Run Date", value: new Date().toLocaleString("en-IN") });
    analyticsSheet.addRow({ kpi: "Total Orders Captured", value: reportData.summary.totalOrders });
    analyticsSheet.addRow({ kpi: "Gross Sales Sum", value: reportData.summary.grossSales });
    analyticsSheet.addRow({ kpi: "Offers Total Discount", value: reportData.summary.offerDiscounts });
    analyticsSheet.addRow({ kpi: "Coupon Total Discount", value: reportData.summary.couponDiscounts });
    analyticsSheet.addRow({ kpi: "Net Revenue Total", value: reportData.summary.netRevenue });

    analyticsSheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    analyticsSheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", `attachment; filename="KAVOX-sales-report-${filter}-${Date.now()}.xlsx"`);

    await workbook.xlsx.write(res);
    res.end();
  } catch (error) {
    console.error("Excel Download Controller Error:", error);
    res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).send("Failed to export Excel sheet.");
  }
};
